In [1]:
import findspark
findspark.init('/home/ubuntu/spark-2.1.1-bin-hadoop2.7')
import pyspark
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('bank').getOrCreate()
bank = spark.read.csv('/home/ubuntu/Loan Defaulter.csv', header=True, inferSchema=True)

In [2]:
print(bank.columns)
print(bank.show)

['SK_ID_CURR', 'TARGET', 'CODE_GENDER', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH', 'OWN_CAR_AGE', 'FLAG_MOBIL', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE', 'FLAG_CONT_MOBILE', 'FLAG_PHONE', 'FLAG_EMAIL', 'CNT_FAM_MEMBERS', 'REGION_RATING_CLIENT', 'REGION_RATING_CLIENT_W_CITY', 'HOUR_APPR_PROCESS_START', 'REG_REGION_NOT_LIVE_REGION', 'REG_REGION_NOT_WORK_REGION', 'LIVE_REGION_NOT_WORK_REGION', 'REG_CITY_NOT_LIVE_CITY', 'REG_CITY_NOT_WORK_CITY', 'LIVE_CITY_NOT_WORK_CITY']
<bound method DataFrame.show of DataFrame[SK_ID_CURR: int, TARGET: int, CODE_GENDER: string, CNT_CHILDREN: int, AMT_INCOME_TOTAL: double, AMT_CREDIT: double, AMT_ANNUITY: double, AMT_GOODS_PRICE: double, REGION_POPULATION_RELATIVE: double, DAYS_BIRTH: int, DAYS_EMPLOYED: int, DAYS_REGISTRATION: int, DAYS_ID_PUBLISH: int, OWN_CAR_AGE: int, FLAG_MOBIL: int, FLAG_EMP_PHONE: int, FLAG_WORK_PHONE: int, FLAG_CONT_MOBILE: int, FLAG_PHONE: int, FLAG_EMAIL: int, CNT_FAM_MEMBERS: int, REGION_RATING_CLIENT: int, REGION_RATING_CLIENT_W_CITY: int, HOUR_APPR_PROCESS_START: int, REG_REGION_NOT_LIVE_REGION: int, REG_REGION_NOT_WORK_REGION: int, LIVE_REGION_NOT_WORK_REGION: int, REG_CITY_NOT_LIVE_CITY: int, REG_CITY_NOT_WORK_CITY: int, LIVE_CITY_NOT_WORK_CITY: int]>

In [3]:
bank.printSchema()

root
 |-- SK_ID_CURR: integer (nullable = true)
 |-- TARGET: integer (nullable = true)
 |-- CODE_GENDER: string (nullable = true)
 |-- CNT_CHILDREN: integer (nullable = true)
 |-- AMT_INCOME_TOTAL: double (nullable = true)
 |-- AMT_CREDIT: double (nullable = true)
 |-- AMT_ANNUITY: double (nullable = true)
 |-- AMT_GOODS_PRICE: double (nullable = true)
 |-- REGION_POPULATION_RELATIVE: double (nullable = true)
 |-- DAYS_BIRTH: integer (nullable = true)
 |-- DAYS_EMPLOYED: integer (nullable = true)
 |-- DAYS_REGISTRATION: integer (nullable = true)
 |-- DAYS_ID_PUBLISH: integer (nullable = true)
 |-- OWN_CAR_AGE: integer (nullable = true)
 |-- FLAG_MOBIL: integer (nullable = true)
 |-- FLAG_EMP_PHONE: integer (nullable = true)
 |-- FLAG_WORK_PHONE: integer (nullable = true)
 |-- FLAG_CONT_MOBILE: integer (nullable = true)
 |-- FLAG_PHONE: integer (nullable = true)
 |-- FLAG_EMAIL: integer (nullable = true)
 |-- CNT_FAM_MEMBERS: integer (nullable = true)
 |-- REGION_RATING_CLIENT: integer (nullable = true)
 |-- REGION_RATING_CLIENT_W_CITY: integer (nullable = true)
 |-- HOUR_APPR_PROCESS_START: integer (nullable = true)
 |-- REG_REGION_NOT_LIVE_REGION: integer (nullable = true)
 |-- REG_REGION_NOT_WORK_REGION: integer (nullable = true)
 |-- LIVE_REGION_NOT_WORK_REGION: integer (nullable = true)
 |-- REG_CITY_NOT_LIVE_CITY: integer (nullable = true)
 |-- REG_CITY_NOT_WORK_CITY: integer (nullable = true)
 |-- LIVE_CITY_NOT_WORK_CITY: integer (nullable = true)

In [4]:
bank.createOrReplaceTempView("bank")
bank = spark.sql("SELECT * FROM bank WHERE TARGET = 1 ")
import pandas as pd
pd.DataFrame(bank.take(bank.count()), columns=bank.columns)

,SK_ID_CURR,TARGET,CODE_GENDER,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,...,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY
0,100002,1,M,0,202500.0,406597.5,24700.5,351000.0,0.018801,-9461,...,1,2,2,10,0,0,0,0,0,0
1,100031,1,F,0,112500.0,979992.0,27076.5,702000.0,0.018029,-18724,...,1,3,2,9,0,0,0,0,0,0
2,100047,1,M,0,202500.0,1193580.0,35028.0,855000.0,0.025164,-17482,...,2,2,2,9,0,0,0,0,0,0
3,100049,1,F,0,135000.0,288873.0,16258.5,238500.0,0.007305,-13384,...,2,3,3,11,0,0,0,0,0,0
4,100096,1,F,0,81000.0,252000.0,14593.5,252000.0,0.028663,-24794,...,2,2,2,10,0,0,0,0,0,0
5,100112,1,M,0,315000.0,953460.0,64107.0,900000.0,0.030755,-10199,...,1,2,2,13,0,0,0,0,1,1
6,100130,1,F,1,157500.0,723996.0,30802.5,585000.0,0.007274,-10526,...,2,2,2,12,0,1,1,0,1,1
7,100160,1,M,0,292500.0,675000.0,36747.0,675000.0,0.035792,-16667,...,2,2,2,18,1,1,0,1,1,0
8,100181,1,F,0,157500.0,245619.0,12667.5,166500.0,0.022625,-17538,...,1,2,2,9,0,0,0,0,0,0
9,100192,1,F,0,111915.0,225000.0,21037.5,225000.0,0.018801,-7989,...,1,2,2,16,0,0,0,0,1,1
10,100209,1,M,3,180000.0,540000.0,27000.0,540000.0,0.024610,-15326,...,5,2,2,18,0,0,0,0,0,0
11,100214,1,F,1,202500.0,436032.0,28516.5,360000.0,0.032561,-10127,...,3,1,1,14,0,0,0,0,0,0
12,100246,1,F,0,135000.0,495216.0,26995.5,427500.0,0.008019,-12824,...,2,2,2,10,0,0,0,0,0,0
13,100273,1,F,0,157500.0,1710000.0,66262.5,1710000.0,0.004849,-23127,...,2,2,2,10,0,0,0,0,0,0
14,100282,1,F,0,73341.0,135000.0,6750.0,135000.0,0.018801,-9157,...,1,2,2,11,0,0,0,0,0,0
15,100286,1,M,1,121500.0,263686.5,17298.0,238500.0,0.014464,-17847,...,3,2,2,5,0,0,0,0,0,0
16,100295,1,M,1,225000.0,1019205.0,31032.0,774000.0,0.072508,-11356,...,2,1,1,14,1,0,1,0,0,0
17,100300,1,M,0,63000.0,426645.0,22468.5,324000.0,0.018634,-12209,...,1,2,2,10,0,0,0,0,0,0
18,100301,1,M,1,112500.0,571486.5,31131.0,454500.0,0.022625,-8292,...,3,2,2,11,0,0,0,0,0,0
19,100326,1,M,0,36000.0,284400.0,10849.5,225000.0,0.018209,-22078,...,2,3,3,7,0,0,0,0,0,0
20,100336,1,F,0,157500.0,497520.0,28692.0,450000.0,0.024610,-13989,...,1,2,2,15,0,0,0,0,0,0
21,100396,1,M,0,112500.0,417024.0,25330.5,360000.0,0.025164,-13707,...,1,2,2,10,0,0,0,0,0,0
22,100401,1,F,0,202500.0,343683.0,16663.5,261000.0,0.010966,-20200,...,1,2,2,10,0,0,0,0,0,0
23,100424,1,M,0,112500.0,117162.0,12433.5,103500.0,0.018850,-18302,...,1,2,2,11,0,0,0,0,1,1
24,100439,1,M,0,81000.0,312840.0,22891.5,247500.0,0.018850,-8038,...,2,2,2,17,0,0,0,1,1,0
25,100452,1,M,1,171000.0,1009566.0,36391.5,904500.0,0.025164,-18767,...,3,2,2,8,0,0,0,0,0,0
26,100472,1,M,1,135000.0,545040.0,26509.5,450000.0,0.008474,-13923,...,3,2,2,15,0,0,0,0,0,0
27,100477,1,M,1,112500.0,284400.0,22599.0,225000.0,0.015221,-13715,...,3,2,2,8,0,0,0,0,1,1
28,100485,1,M,1,270000.0,810000.0,40500.0,810000.0,0.026392,-11353,...,3,2,2,9,0,0,0,0,0,0
29,100490,1,M,0,135000.0,755190.0,38686.5,675000.0,0.009630,-9684,...,1,2,2,11,0,1,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2512,136321,1,F,0,180000.0,585000.0,32796.0,585000.0,0.028663,-18433,...,2,2,2,8,0,0,0,0,0,0
2513,136329,1,F,1,180000.0,562491.0,27189.0,454500.0,0.018801,-16747,...,3,2,2,10,0,0,0,0,0,0
2514,136341,1,M,0,202500.0,536917.5,30109.5,463500.0,0.035792,-18300,...,1,2,2,14,0,0,0,0,0,0
2515,136351,1,F,0,112500.0,657000.0,27967.5,657000.0,0.028663,-22206,...,2,2,2,8,0,0,0,0,0,0
2516,136352,1,F,0,258750.0,315666.0,22576.5,292500.0,0.020713,-21256,...,2,3,3,7,0,0,0,0,0,0
2517,136360,1,F,2,112500.0,738567.0,23953.5,616500.0,0.010006,-13690,...,4,2,2,13,0,0,0,0,0,0
2518,136362,1,F,0,157500.0,1339690.5,56889.0,1156500.0,0.018801,-19774,...,2,2,2,15,0,0,0,0,1,1
2519,136369,1,F,0,112500.0,942300.0,30397.5,675000.0,0.035792,-22545,...,1,2,2,14,0,0,0,1,1,0
2520,136370,1,F,0,63000.0,382500.0,16978.5,382500.0,0.018801,-12397,...,2,2,2,7,0,0,0,0,1,1
2521,136391,1,M,0,382500.0,983299.5,39123.0,904500.0,0.072508,-17152,...,2,1,1,13,0,1,1,0,0,0
2522,136398,1,M,0,157500.0,359725.5,13689.0,297000.0,0.006852,-13128,...,2,3,3,6,0,0,0,0,0,0
2523,136410,1,M,0,90000.0,354276.0,17361.0,292500.0,0.020246,-8083,...,1,3,3,10,0,0,0,0,0,0
2524,136419,1,M,0,135000.0,284256.0,27819.0,270000.0,0.035792,-25032,...,1,2,2,11,0,0,0,0,0,0
2525,136431,1,F,0,103500.0,225000.0,12334.5,225000.0,0.018209,-9819,...,1,3,3,11,0,0,0,0,0,0
2526,136469,1,F,1,117000.0,537669.0,25195.5,378000.0,0.008575,-14498,...,3,2,2,17,0,0,0,0,0,0
2527,136486,1,F,0,63000.0,292500.0,8329.5,292500.0,0.010556,-23882,...,1,3,3,10,0,0,0,0,0,0
2528,136496,1,M,0,166500.0,505642.5,34335.0,436500.0,0.030755,-16506,...,2,2,2,9,0,0,0,0,0,0
2529,136510,1,F,0,180000.0,1575000.0,54877.5,1575000.0,0.001417,-19065,...,2,2,2,15,0,0,0,0,1,1
2530,136516,1,M,0,225000.0,550980.0,43659.0,450000.0,0.006852,-13344,...,2,3,3,6,0,0,0,0,0,0
2531,136526,1,M,0,337500.0,1078200.0,38331.0,900000.0,0.019101,-11084,...,1,2,2,13,0,0,0,0,1,1
2532,136527,1,M,0,153000.0,247500.0,18139.5,247500.0,0.006671,-11493,...,2,2,2,12,0,0,0,0,0,0
2533,136534,1,F,2,99000.0,508495.5,24592.5,454500.0,0.018209,-12075,...,4,3,3,14,0,0,0,0,1,1
2534,136592,1,M,1,202500.0,450000.0,24543.0,450000.0,0.028663,-13053,...,3,2,2,10,0,0,0,0,0,0
2535,136595,1,M,1,148500.0,1078200.0,34911.0,900000.0,0.022800,-10010,...,3,2,2,10,0,0,0,0,0,0
2536,136610,1,F,0,146250.0,497520.0,31923.0,450000.0,0.020246,-24348,...,2,3,3,8,0,0,0,0,0,0
2537,136637,1,F,0,247500.0,1374480.0,45553.5,1125000.0,0.072508,-13981,...,1,1,1,15,0,0,0,0,0,0
2538,136651,1,M,0,229500.0,270000.0,21460.5,270000.0,0.028663,-18132,...,2,2,2,12,0,0,0,0,0,0
2539,136676,1,F,1,157500.0,648000.0,23404.5,648000.0,0.028663,-15826,...,3,2,2,13,0,0,0,0,0,0
2540,136682,1,F,0,180000.0,415224.0,11416.5,328500.0,0.031329,-18708,...,1,2,2,13,0,0,0,0,0,0
2541,136727,1,F,0,79650.0,760225.5,30150.0,679500.0,0.018634,-23126,...,2,2,2,14,0,0,0,0,0,0

In [5]:
bank.createOrReplaceTempView("bank")
bank = spark.sql("SELECT * FROM bank WHERE TARGET = 0 and CODE_GENDER = 'F' ")
import pandas as pd
pd.DataFrame(bank.take(bank.count()), columns=bank.columns)

Empty DataFrame
Columns: [SK_ID_CURR, TARGET, CODE_GENDER, CNT_CHILDREN, AMT_INCOME_TOTAL, AMT_CREDIT, AMT_ANNUITY, AMT_GOODS_PRICE, REGION_POPULATION_RELATIVE, DAYS_BIRTH, DAYS_EMPLOYED, DAYS_REGISTRATION, DAYS_ID_PUBLISH, OWN_CAR_AGE, FLAG_MOBIL, FLAG_EMP_PHONE, FLAG_WORK_PHONE, FLAG_CONT_MOBILE, FLAG_PHONE, FLAG_EMAIL, CNT_FAM_MEMBERS, REGION_RATING_CLIENT, REGION_RATING_CLIENT_W_CITY, HOUR_APPR_PROCESS_START, REG_REGION_NOT_LIVE_REGION, REG_REGION_NOT_WORK_REGION, LIVE_REGION_NOT_WORK_REGION, REG_CITY_NOT_LIVE_CITY, REG_CITY_NOT_WORK_CITY, LIVE_CITY_NOT_WORK_CITY]
Index: []

[0 rows x 30 columns]